Program       ::= Statement* EOF

Statement     ::= Declaration NEWLINE
                | DeclarationInitilasation NEWLINE
                | Assignment NEWLINE
                | IfStatement
                | WhileStatement
                | ForEachNormal
                | ForEachEdge
                | RepeatStatement
                | Algorithm
                | Expression NEWLINE 
                | ExprEdge NEWLINE
                | NodeDec NEWLINE
                | ExprGraph NEWLINE
                | LoopModifier NEWLINE
                | GraphDecl
                | DisplayStatement
                | ReturnStatement

ListExpression ::= '[' ListExpression (',' ListExpression)* ']'
                | Expression

IfStatement ::= 'if' Expression 'then' NEWLINE INDENT Statement+ DEDENT ('else' NEWLINE INDENT Statement+ DEDENT)?
WhileStatement ::= 'while' Expression 'then' NEWLINE INDENT Statement+ DEDENT
ForEachNormal ::= 'for each' IDENTIFIER 'in' Expression NEWLINE INDENT Statement+ DEDENT
ForEachEdge ::= 'for each' ExprEdge ('with weight' IDENTIFIER)? 'in' IDENTIFIER NEWLINE INDENT Statement+ DEDENT
RepeatStatement ::= 'repeat' Expression 'times' NEWLINE INDENT Statement+ DEDENT

DisplayStatement ::= 'display' Expression NEWLINE
ReturnStatement ::= 'return' Expression NEWLINE

Expression    ::= ExprAnd ('or' ExprAnd)* 
                | 'weight of' IDENTIFIER '.' IDENTIFIER ('---' | '-->') IDENTIFIER
                | ExprNode
ExprAnd       ::= ExprEq ('and' ExprEq)*
ExprEq        ::= ExprRel (('=' | '!=') ExprRel)*
ExprRel       ::= ExprPlus (('<' | '>' | '<=' | '>=') ExprPlus)*
ExprPlus      ::= ExprMult (('+' | '-') ExprMult)*
ExprMult      ::= ExprExp (('*' | '/' | '%') ExprExp)*
ExprExp       ::= ExprNot ('^' ExprNot)*
ExprNot       ::= ('neg' | '-')? ExprCall
ExprCall      ::= '(' Expression ')'
                | AbsoluteValue 
                | Magnitude 
                | FunctionCall
                | ArrayAccess
                | IDENTIFIER '.' ExprCall
                | Term
Term          ::= BOOL_VALUE | INTEGER_NUMBER | NATURAL_NUMBER | REAL_NUMBER | TEXT | IDENTIFIER 

FunctionCall ::= IDENTIFIER '(' ArgList? ')'
ArgList ::= Expression (',' Expression)*

ArrayAccess ::= IDENTIFIER ('[' Expression ']')+
AbsoluteValue ::= '|' Expression '|'
Magnitude ::= '||' Expression '||'

ExprGraph     ::= IDENTIFIER ('add' | 'remove') (TYPE_NODE IDENTIFIER | ExprEdge)
ExprNode      ::= '(' Expression ')---' 
                | '(' Expression ')-->' 
                | '(' Expression ')<--'
                | '(' Expression ')<->'
ExprEdge      ::= TYPE_EDGE IdentifierAccess ('---' | '-->' | '<--' | '<->') IdentifierAccess (',' IdentifierAccess)* ('weight' Expression (',' Expression)*)?

Algorithm     ::= 'algo' IDENTIFIER '(' (Parameter (',' Parameter)* )? ')' ('return' TYPE)? NEWLINE INDENT Statement+ DEDENT
Parameter     ::= IDENTIFIER 'in' TYPE_ARITH 
                | (TYPE_GRAPH | TYPE_OTHER | TYPE_NODE) IDENTIFIER

LoopModifier  ::= 'stop'

GraphDecl     ::= TYPE_GRAPH IDENTIFIER ('with' TYPE_ARITH 'weight')? NEWLINE (INDENT (NodeDec NEWLINE | ExprEdge NEWLINE )+ DEDENT)?

NodeDec     ::= TYPE_NODE (IDENTIFIER (',' IDENTIFIER)* | IDENTIFIER ':=' Expression)

Declaration ::= IDENTIFIER (',' IDENTIFIER)* 'in' TYPE_ARITH | TYPE_OTHER IDENTIFIER (',' IDENTIFIER)* | IDENTIFIER DIMENSION? 'list' 'in' TYPE
DeclarationInitilasation ::= IDENTIFIER 'in' TYPE_ARITH ':=' Expression | TYPE_OTHER IDENTIFIER ':=' Expression | IDENTIFIER DIMENSION? 'list' 'in' TYPE ':=' '[' ListExpression (',' ListExpression)* ']'

Assignment ::= IdentifierAccess ':=' Expression

IdentifierAccess ::= IDENTIFIER ('.' IDENTIFIER)* ('.' FunctionCall | '.' ArrayAccess)?


<?TOKENS?>

INTEGER_NUMBER     ::= '-'?('0'|[1-9][0-9]*) 
NATURAL_NUMBER     ::= '0'|[1-9][0-9]*
INTEGER_NUMBER     <<  NATURAL_NUMBER

REAL_NUMBER        ::= '-'?('0'|[1-9][0-9]*)'.'[0-9]*

IDENTIFIER         ::= ([a-zA-Z_][a-zA-Z0-9_]*) - (KEYWORD)
TEXT?              ::= '"' .* '"'
TYPE_ARITH         ::= 'int' | 'nat' | 'real'
TYPE_GRAPH         ::= 'graph' | 'digraph' | 'tree'
TYPE_OTHER         ::= 'text' | 'bool'
TYPE_EDGE          ::= 'edge'
TYPE_NODE          ::= 'node'

TYPE               ::= TYPE_ARITH | TYPE_GRAPH | TYPE_OTHER | TYPE_NODE 

BOOL_VALUE         ::= 'true' | 'false'

NEWLINE            ::= '@NEWLINE'
INDENT             ::= '@INDENT'
DEDENT             ::= '@DEDENT'
EOF                ::= $ | '$'

KEYWORD            ::= 'or'
                     | 'and'
                     | 'neg'
                     | 'true'
                     | 'false'
                     | 'bool'
                     | 'int'
                     | 'real'
                     | 'nat'
                     | 'graph'
                     | 'digraph'
                     | 'tree'
                     | 'text'
                     | 'bool'
                     | 'edge'
                     | 'node'
                     | 'in'
                     | 'if'
                     | 'else'
                     | 'while'
                     | 'for each'
                     | 'weight'
                     | 'repeat'
                     | 'times'
                     | 'algo'
                     | 'stop'
                     | 'display'
                     | 'return'
                     | 'add'
                     | 'remove'
                     | 'list'

DIMENSION   ::= ([1-9][0-9]*)'d'

Whitespace ::= [ #x9#xA]+
                /*ws: definition*/